### ISSUE TITLE
Error: Cannot find module './handlers/get.js'

### ISSUE THREAD

**Issue by nvx0** [authenticname/sharex-server#22]
Error: Cannot find module './handlers/get.js'

while trying to run sever

**Comment by alexthemaster** [comment]
Hey! Are you manually using it or using it via Docker?
If manually then make sure your Node.js version is up to date. If that doesn't fix it then please write the steps you used so I could replicate the error.

**Comment by falseCloud** [comment]
I use it via Docker

**Comment by alexthemaster** [comment]
That's weird. I've built a Docker image from the ground up and it worked for me. Try removing your local image using `docker rmi sharex-server` and building it again.
